web:
  image: phanbook/nginx
  ports:
    - "80:80"
  volumes:
    - ./:/var/www/html
    - ./opsfiles/docker/templates/phanbook.conf:/etc/nginx/sites-enabled/default
  links:
    - php
php:
  image: phanbook/php
  volumes:
    - ./opsfiles/docker/templates/php-fpm.conf:/etc/php5/fpm/php-fpm.conf
    - ./:/var/www/html
  links:
    - db
app:
  image: phanbook/app
  working_dir: /var/www/html
  volumes:
    - ./:/var/www/html
db:
  image: phanbook/mysql
  #volumes:
  #  - /opt/mysql/data:/var/lib/mysql
  #environment:
  #  - MYSQL_DB=phanbook
  #  - MYSQL_PASS=phanbook
  #  - MYSQL_USER=phanbook
  env_file: ./opsfiles/docker/config.env
